version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: ./.docker/web/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8050:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - database
    env_file: .env
  database:
    image: mysql:5.6
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
    ports:
      - "3306:3306"